# 指定运行端口
server:
  port: 8002

# 指定服务名称
spring:
  application:
    name: eureka-server1
  profiles: replica1

# 指定主机地址
eureka:
  instance:
    hostname: replica1
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      # 注册到另一个Eureka注册中心
      defaultZone: http://replica2:8003/eureka/